#Compose version:
version: '2'

# Stack Name: "monitor"

#######################################################
#                    VARIABLE LIST                    #
#######################################################

#################### PORTS ####################
# HOST_PORT
#   - The port on the host on which the site will be accessible

#################### WEBSITE ####################
# SITE_NAME
#   - Site name (lowercase without spaces)
#  SITE_URL
#   - Site URL (without subdomain. A naked and a "www" subdomain entry is added automatically)

#################### DATABASE ####################
# DATABASE_PASSWORD
#   - You normally won't have to manually enter this anywhere, so make it complex
# MYSQL_ROOT_PASSWORD
#   - You normally won't have to manually enter this anywhere, so make it complex and different from the database password

#################### REVERSE PROXY AND LETSENCRYPT ####################
# REVERSE_PROXY_LETSENCRYPT_ENABLED
#   - Use a single space (" ") for enabled, and a hashtag ("#") for disabled
# REVERSE_PROXY_NETWORK
#   - The external Docker network the reverse proxy runs on
# LETSENCRYPT_EMAIL
#   - The email address to use with Let's Encrypt


####################################################
#                    CONTAINERS                    #
####################################################
services:


#################### WORDPRESS INSTALLATION ####################

services:
# Wordpress Installation
  website-${SITE_NAME}-wordpress:
    hostname: ${SITE_NAME}
    image: wordpress:latest
    ports:
      - ${HOST_PORT}:80
    volumes:
      # Timezone
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # Configuration
      - website-${SITE_NAME}-wordpress:/var/www/html
    restart: unless-stopped
    environment:
      # Reverse Proxy and SSL
${REVERSE_PROXY_LETSENCRYPT_ENABLED}     - VIRTUAL_PORT=${HOST_PORT}
${REVERSE_PROXY_LETSENCRYPT_ENABLED}     - VIRTUAL_HOST=${SITE_URL},www.${SITE_URL}
${REVERSE_PROXY_LETSENCRYPT_ENABLED}     - LETSENCRYPT_HOST=${SITE_URL},www.${SITE_URL}
${REVERSE_PROXY_LETSENCRYPT_ENABLED}     - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      # Container Specific
      - WORDPRESS_DB_HOST=${SITE_NAME}-database:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=${DATABASE_PASSWORD}
      - WORDPRESS_DB_NAME=wordpress
    networks:
      - ${REVERSE_PROXY_NETWORK}
      - ${SITE_NAME}

# Database
  ${SITE_NAME}-database:
    hostname: ${SITE_NAME}-database
    image: mysql:latest
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      # Timezone
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # Configuration
      - website-${SITE_NAME}-database:/var/lib/mysql
    restart: unless-stopped
    environment:
      # Container Specific
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - ${SITE_NAME}


####################################################
#                    NETWORKS                    #
####################################################
networks:

#################### REVERSE PROXY ####################
  ${REVERSE_PROXY_NETWORK}:
    external: true